# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/axel/EpiScan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/axel/EpiScan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axel/EpiScan/CMakeFiles /home/axel/EpiScan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axel/EpiScan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named episcan_core

# Build rule for target.
episcan_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 episcan_core
.PHONY : episcan_core

# fast build rule for target.
episcan_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan_core.dir/build.make CMakeFiles/episcan_core.dir/build
.PHONY : episcan_core/fast

#=============================================================================
# Target rules for targets named episcan-cli

# Build rule for target.
episcan-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 episcan-cli
.PHONY : episcan-cli

# fast build rule for target.
episcan-cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan-cli.dir/build.make CMakeFiles/episcan-cli.dir/build
.PHONY : episcan-cli/fast

#=============================================================================
# Target rules for targets named episcan

# Build rule for target.
episcan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 episcan
.PHONY : episcan

# fast build rule for target.
episcan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan.dir/build.make CMakeFiles/episcan.dir/build
.PHONY : episcan/fast

src/app/ScannerEngine.o: src/app/ScannerEngine.cpp.o
.PHONY : src/app/ScannerEngine.o

# target to build an object file
src/app/ScannerEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan_core.dir/build.make CMakeFiles/episcan_core.dir/src/app/ScannerEngine.cpp.o
.PHONY : src/app/ScannerEngine.cpp.o

src/app/ScannerEngine.i: src/app/ScannerEngine.cpp.i
.PHONY : src/app/ScannerEngine.i

# target to preprocess a source file
src/app/ScannerEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan_core.dir/build.make CMakeFiles/episcan_core.dir/src/app/ScannerEngine.cpp.i
.PHONY : src/app/ScannerEngine.cpp.i

src/app/ScannerEngine.s: src/app/ScannerEngine.cpp.s
.PHONY : src/app/ScannerEngine.s

# target to generate assembly for a file
src/app/ScannerEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan_core.dir/build.make CMakeFiles/episcan_core.dir/src/app/ScannerEngine.cpp.s
.PHONY : src/app/ScannerEngine.cpp.s

src/cli_main.o: src/cli_main.cpp.o
.PHONY : src/cli_main.o

# target to build an object file
src/cli_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan-cli.dir/build.make CMakeFiles/episcan-cli.dir/src/cli_main.cpp.o
.PHONY : src/cli_main.cpp.o

src/cli_main.i: src/cli_main.cpp.i
.PHONY : src/cli_main.i

# target to preprocess a source file
src/cli_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan-cli.dir/build.make CMakeFiles/episcan-cli.dir/src/cli_main.cpp.i
.PHONY : src/cli_main.cpp.i

src/cli_main.s: src/cli_main.cpp.s
.PHONY : src/cli_main.s

# target to generate assembly for a file
src/cli_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan-cli.dir/build.make CMakeFiles/episcan-cli.dir/src/cli_main.cpp.s
.PHONY : src/cli_main.cpp.s

src/gui_main.o: src/gui_main.cpp.o
.PHONY : src/gui_main.o

# target to build an object file
src/gui_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan.dir/build.make CMakeFiles/episcan.dir/src/gui_main.cpp.o
.PHONY : src/gui_main.cpp.o

src/gui_main.i: src/gui_main.cpp.i
.PHONY : src/gui_main.i

# target to preprocess a source file
src/gui_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan.dir/build.make CMakeFiles/episcan.dir/src/gui_main.cpp.i
.PHONY : src/gui_main.cpp.i

src/gui_main.s: src/gui_main.cpp.s
.PHONY : src/gui_main.s

# target to generate assembly for a file
src/gui_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episcan.dir/build.make CMakeFiles/episcan.dir/src/gui_main.cpp.s
.PHONY : src/gui_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... episcan"
	@echo "... episcan-cli"
	@echo "... episcan_core"
	@echo "... src/app/ScannerEngine.o"
	@echo "... src/app/ScannerEngine.i"
	@echo "... src/app/ScannerEngine.s"
	@echo "... src/cli_main.o"
	@echo "... src/cli_main.i"
	@echo "... src/cli_main.s"
	@echo "... src/gui_main.o"
	@echo "... src/gui_main.i"
	@echo "... src/gui_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

